version: '3'
services:

  # The jenkins build server for our environment
  jenkins:
    image: jenkins-dockerbuilder
    ports: 
     - "8080"
     - "50000"
    volumes: 
     - jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      build_network:
        aliases:
         - jenkins
    environment:
     - ADMIN_PASSWORD=ChangeMe!
  
  registry:
    image: registry:2
    ports:
     - "5000"
    volumes:
     - docker_registry:/var/lib/registry  
    networks:
      build_network:
        aliases:
          - registry

networks:
  build_network:

volumes: 
  jenkins_home:
  docker_registry: