version: '3'
services:

  # The jenkins build server for our environment
  jenkins:
    image: jenkins-dockerbuilder
    ports: 
     - "8080"
     - "50000"
    volumes: 
     - jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      build_network:
        aliases:
         - jenkins
         - jenkins.local
    environment:
     - ADMIN_PASSWORD=ChangeMe!
  
  registry:
    image: registry:2
    ports:
     - "5000"
     - "443"
    volumes:
     - docker_registry:/var/lib/registry  
     - ~/certs:/certs #TODO: Update and document
    networks:
      build_network:
        aliases:
          - registry.local
          - registry
    environment: 
     - REGISTRY_HTTP_ADDR=0.0.0.0:443
     - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.local.crt
     - REGISTRY_HTTP_TLS_KEY=/certs/registry.local.key

networks:
  build_network:

volumes: 
  jenkins_home:
  docker_registry: