pipeline {

    agent any
    
    stages {
        stage('Build') {
            steps {
                sh 'cd jenkins'
                sh 'sudo docker build -t myjenkins .'
            }
        }
        stage('Test') {
            steps {
                sh 'echo This is my test stage'
            }
        }
        stage('Tag and Upload') {
            steps {
                sh 'echo This is my tag and upload stage'
            }
        }
    }

}