pipeline {

    agent any

    environment {
        DOCKERFILE_DIR = 'jenkins'
        IMAGE_NAME = 'jenkins-dockerbuilder'
        TAG = 'latest'
    }
    
    stages {
        stage('Build') {
            steps {

                // Change to the path where our Dockerfile is located.
                dir ( env.DOCKERFILE_DIR ){

                    // Run the build
                    script {
                        def dockerimage = docker.build("${env.IMAGE_NAME}:${env.TAG}")
                    }
                    
                }
                
            }
        }
        stage('Test') {
            steps {
                sh 'echo These are some fancy tests'
            }
        }
        stage('Tag and Upload') {
            steps {
                sh 'echo This is my tag and upload stage'
            }
        }
    }

}